### ISSUE TITLE
arrow functions without { }

### ISSUE THREAD

**Issue by andreendo** [ValYouW/njsTrace#12]
Hi,

It seems that it can track functions like:

() => { console.log('abc') }

but not like:

() => console.log('abc')

Regards,

**Comment by ValYouW** [comment]
Yeah, that's tricky as there is no body function where I can inject the tracing code in...

**Comment by coderaiser** [comment]
This can be solved easily with help of [putout code transformer](https://github.com/coderaiser/putout/issues/61), here is how it can look like:
![image](https://user-images.githubusercontent.com/1573141/121949769-87468680-cd61-11eb-9f4b-885f95d9816d.png)

Also as I understand `ESM` not supported because it requires using [loaders](https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#esm_loaders), right?

**Comment by ValYouW** [comment]
Hi,
Thx.
Never looked on ESM to be honest...

**Comment by coderaiser** [comment]
> Hi,
Thx.
Never looked on ESM to be honest...

Just landed `putout-based` `function tracer` [ESTrace](https://github.com/coderaiser/estrace) for ESM.

**Comment by retorquere** [comment]
> This can be solved easily with help of [putout code transformer](https://github.com/coderaiser/putout/issues/61), here is how it can look like:

Isn't there a `return a` missing in that codemod result? `(a) => a` means "return the input"

**Comment by coderaiser** [comment]
> Isn't there a return a missing in that codemod result? (a) => a means "return the input"

Yes, you right, thank you! Fixed with https://github.com/coderaiser/estrace/commit/386c44c6559345d3f81342cee3703a66f25b9825, landed in [v1.1.0](https://github.com/coderaiser/estrace/releases/tag/v1.1.0) 🎉 . 

@ValYouW you are done a really great job with `njsTrace`!

> Instrumentation just adds calls to njstrace tracing methods at the beginning of each function, at the end of each function, and before any return statement.

I just tried a couple different ways:
- Wrap all functions with a `__estrace` call:
```js
hello(__esTrace('name', 'url', function(word) {
    return `hello ${word}`;
}));
```
But it has problems when we have function with `ExportNamedDeclaration` with `FunctionDeclaration`:

```js
export function hello() {
}
```

will be converted to:

```js
// invalid
export __esTrace('name', 'url', function() {
});
```

Which has invalid syntax.
- `bind` `__estrace` with `context` and `args`:

```js
function hello() {
    return esTrace.bind(this, 'hello', 'file://1.js', function hello() {
    });
};
```

Has problems with:

```js
const a = (b) => (c) => d;
``` 

Because of recursion while building (and possible executing) instrumented code.

So your way is the best, thank you!

**Comment by retorquere** [comment]
Can I reuse this plugin in my own build (esbuild.js)? I have a private copy currently and that will grow stale.

**Comment by coderaiser** [comment]
> Can I reuse this plugin in my own build (esbuild.js)? I have a private copy currently and that will grow stale.

Of course, why not :)

**Comment by retorquere** [comment]
No, I mean, was it published in such a way that I can npm install it as-is as a putout plugin?

**Comment by coderaiser** [comment]
> No, I mean, was it published in such a way that I can npm install it as-is as a putout plugin?

Yes [you can](https://github.com/coderaiser/estrace#using-as-plugin), it will look like:

```js
import putout from 'putout';
import estracePlugin from 'estrace/plugin';

const source = `
    const fn = (a) => a;
`;

const {code} = putout(source, {
    plugins: [
        ['estrace', estracePlugin],
    ],
});

console.log(code);
```
